export const SET_ALL_GRO_STATS = 'SET_ALL_GRO_STATS';
export const REMOVE_ALL_GRO_STATS = 'REMOVE_ALL_GRO_STATS';
export const SET_PRICE_CHECK = 'SET_PRICE_CHECK';
export const REMOVE_PRICE_CHECK = 'REMOVE_PRICE_CHECK';
